// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAG3g76qI434KiQMv0MixsmS40U-uEQaM',
    appId: '1:269669104910:web:13145c059a8d5159972b5f',
    messagingSenderId: '269669104910',
    projectId: 'sapekderas',
    authDomain: 'sapekderas.firebaseapp.com',
    storageBucket: 'sapekderas.appspot.com',
    measurementId: 'G-KW1YDD7RCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVsmmoU7R-x0Myq4dzcvzyc7adC0t8RM',
    appId: '1:269669104910:android:bd469b1196563df0972b5f',
    messagingSenderId: '269669104910',
    projectId: 'sapekderas',
    storageBucket: 'sapekderas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-Ou9tPZf_iU9JrUfwevL0OGk0GlzEHc',
    appId: '1:269669104910:ios:403a6f17e69c0291972b5f',
    messagingSenderId: '269669104910',
    projectId: 'sapekderas',
    storageBucket: 'sapekderas.appspot.com',
    iosClientId: '269669104910-03bb8oonqp2rp0paeqm22nnt9p9h13dc.apps.googleusercontent.com',
    iosBundleId: 'com.app.sapekderas',
  );
}
